version: '3'

services:
  nginx: 
    image: nginx:latest
    container_name: fsaycon-ray-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.html:/etc/nginx/html/index.html
    ports:
      - 80:80
  ray:
    image: ray-dashboard
    container_name: fsaycon-ray-dashboard
    build: ray-dashboard
    ports: 
      - 8265:8265
    volumes: 
      - ./ray-dashboard:/app
    shm_size: '2gb'
    env_file: ./ray-dashboard/.env
